const ShopActionTypes = {
    UPDATE_COLLECTIONS : 'UPDATE_COLLECTIONS',
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTION_START',
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE : 'FETCH_COLLECTION_FAIL'
}

export default ShopActionTypes;