export const CartActionTypes = {
    TOGGLE_CART_HIDDEN : 'SET_CURRENT_USER', 
    ADD_ITEM : 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART : 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM : 'REMOVE_ITEM',
    FILL_CART : 'FILL_CART',
    EMPTY_CART : 'EMPTY_CART',
}
